# Generated by Django 4.2.11 on 2024-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0020_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('uri', models.URLField(blank=True, help_text='Reference to a controlled vocabulary (eg. NERC)', null=True)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
