# Generated by Django 4.2.9 on 2024-02-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0020_location_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='measure',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='parameter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sensor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='serie',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='station',
            managers=[
            ],
        ),
    ]
