# Generated by Django 4.2.9 on 2024-02-07 10:02

from django.db import migrations


class Migration(migrations.Migration):
    """Inverst the order of the unique_together fields so that when converting the table
    to a hypertable, timescaledb will not complain."""

    dependencies = [
        ('measurements', '0021_alter_location_managers_alter_measure_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together={('timestamp', 'serie')},
        ),
    ]
