# Generated by Django 4.2.9 on 2024-02-07 09:36

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):
    """Change the time field to a TimescaleDateTimeField. This will trigger the creation
    of a timescaledb hypertable in the database."""

    dependencies = [
        ('measurements', '0022_alter_measure_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='timestamp',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 week'),
        ),
    ]
