# Generated by Django 4.2.11 on 2024-06-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0021_physicalparameter'),
        ('measurements', '0023_alter_measure_timestamp'),
    ]

    operations = [
    ]
