# Generated by Django 4.2.11 on 2024-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0023_physicalparameter_series_layer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalparameter',
            old_name='series_layer_options',
            new_name='layer_options',
        ),
    ]
