# Generated by Django 4.2.11 on 2024-07-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0023_alter_measure_timestamp'),
        ('measurements', '0024_rename_series_layer_options_physicalparameter_layer_options'),
    ]

    operations = [
    ]
